### ISSUE TITLE
Track projects by discovery date

### ISSUE THREAD

**Issue by WillNilges** [WillNilges/ShelfLife#50]
What do we do for projects that are 24 weeks old when you turn on shelf life for the first time?

**Comment by WillNilges** [comment]
Database flag. An additional field that indicates if the project has been added in the previous week, and on the week it is discovered, it will send mail to the owners letting them know that their project has been added, how old ShelfLife thinks it is, and that action will be taken starting next week.

**Comment by WillNilges** [comment]
I really want this feature in 1.0.2

**Comment by WillNilges** [comment]
Eh, screw it.

**Comment by WillNilges** [comment]
@mxmeinhold thoughts on simply setting the cronjob to dryrun mode for a week but still setting emails to go off in that week?

**Comment by mxmeinhold** [comment]
What about tracking if you’ve sent emails, and if you haven’t, start with a warning? It’d be nice if this were automated for any shelflife installation. 

Only concern with dry run emails is they are scary emails. Maybe also modify the templates in dry run mode to warn of impending action?

**Comment by WillNilges** [comment]
So, obviously there will be different emails in dryrun mode, and of course this process will be automated, and are you saying the "countdown" to deletion should start with discovery? That might'nt be a bad idea.

**Comment by mxmeinhold** [comment]
I think that might be safer, no surprise nuking.

**Comment by WillNilges** [comment]
I'm going to add a field to the database entry for discovery date. ShelfLife will still track when the project was last touched, but there will be a "write-once"-esque date that controls destructive actions.

**Comment by WillNilges** [comment]
Closed in #61
