### ISSUE TITLE
Create function for spinning down a project

### ISSUE THREAD

**Issue by WillNilges** [WillNilges/ShelfLife#9]
Gotta stop all pods and deployments on a project when they pass the 16 week mark.

https://docs.openshift.com/container-platform/3.7/rest_api/api/v1.Pod.html

**Comment by WillNilges** [comment]
I'm pretty sure I did this... Not totally sure.

**Comment by Tjzabel** [comment]
Interesting! @WillNilges do you have an example of the script for spinning down the deployments? 

This is a cool project :smile: Rust is an *interesting* choice for the platform, though :stuck_out_tongue:

**Comment by WillNilges** [comment]
Thanks, @Tjzabel It's not a script that spins it down, actually. It's a series of API calls. Should be somewhere in the `lib.rs` file. 

As for the platform, I just wanted to write something in Rust. Go might've been better, but Rust is a nice lang.

**Comment by WillNilges** [comment]
:point_up: there it is.
